### ISSUE TITLE
Staircas-timer error

### ISSUE THREAD

**Issue by ErichHeiz** [norganos/node-red-contrib-staircase-timer#1]
HI i got this error when i use the timer

msg : string[61]
"don't know what to do with payload 'undefined' in state 'off'"

thanks
Erich

**Comment by norganos** [comment]
seems like the message passed to the timer does not contain a "payload" value?

the current version expects every input message to be a object with a "payload" property containing one of the understood strings (see Possible Input Payloads in README)

of course it would be possible to perform some more sophisticated heuristics in case there is no such property.

**Comment by ErichHeiz** [comment]
I just reinstalled the staircase timer and now its working.
