### ISSUE TITLE
Boolean out doesn't work

### ISSUE THREAD

**Issue by HLeithner** [norganos/node-red-contrib-staircase-timer#3]
In case of false the component outputs "off" instead of false:

![image](https://github.com/norganos/node-red-contrib-staircase-timer/assets/1497730/b3dd7baa-b63d-478c-8b5c-0f27ff16d7fc)

**Comment by norganos** [comment]
thanks for noticing and creating this issue. it should now work as expected with release 1.0.3

**Comment by HLeithner** [comment]
thx will try later
